# -*- coding: utf-8 -*-
"""Project Telco - Feature Selection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c5Xf4VxWvcTg0SKgRMwgWnLFg7Eiqc6P
"""

import pandas as pd
import io

from google.colab import files
data_to_load = files.upload()
    
df_master = pd.read_csv(io.BytesIO(data_to_load['dqlab_telco_encoded.csv']), error_bad_lines=False)

df = df_master.copy()
df.head()

#Determining numerical variable 
num = df[["tenure","MonthlyCharges","TotalCharges","Churncode"]]
num.head()

#Creating heatmap
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,10))
cor = num.corr()
sns.heatmap(cor, annot=True, cmap=plt.cm.Reds)
plt.show()

#Correlation with output variable
cor_target = abs(cor["Churncode"])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.1]
relevant_features

#Ensuring that there is no correlation between variables
print(df[["tenure","MonthlyCharges"]].corr())
print(df[["tenure","TotalCharges"]].corr())
print(df[["MonthlyCharges","TotalCharges"]].corr())

df.head()

#Determining categorical variable 
cat = df[["UpdatedAt","customerID","gendercode","SeniorCitizen","Partnercode","Dependentscode","PhoneServicecode","MultipleLinescode","InternetServicecode","OnlineSecuritycode","OnlineBackupcode","DeviceProtectioncode","TechSupportcode","StreamingTVcode","StreamingMoviescode","Contractcode","PaperlessBillingcode","PaymentMethodcode","Churncode"]]
cat.head()

#Writing the code of Kendall's for categorical variables
import numpy as np
kendalls = cat.corr(method='kendall')
relevant_features = kendalls[kendalls>0.1]
relevant_features

#Ensuring that there is no correlation between variables
print(df[["SeniorCitizen","PaperlessBillingcode"]].corr())