# -*- coding: utf-8 -*-
"""Project Telco - Encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d8GKlPBF3VDseXov7uCboh20Lu5-ChNY
"""

import pandas as pd
import io

from google.colab import files
data_to_load = files.upload()
    
df_master = pd.read_csv(io.BytesIO(data_to_load['dqlab_telco_clean.csv']), error_bad_lines=False)

df = df_master.copy()

df.info()

#Scikit-Learn library to Encode
from sklearn.preprocessing import LabelEncoder

lb_Gender = LabelEncoder()
df["gendercode"] = lb_gender.fit_transform(df["gender"])

lb_Partner = LabelEncoder()
df["Partnercode"] = lb_Partner.fit_transform(df["Partner"])

lb_Dependents = LabelEncoder()
df["Dependentscode"] = lb_Dependents.fit_transform(df["Dependents"])

lb_PhoneService = LabelEncoder()
df["PhoneServicecode"] = lb_PhoneService.fit_transform(df["PhoneService"])

lb_MultipleLines = LabelEncoder()
df["MultipleLinescode"] = lb_MultipleLines.fit_transform(df["MultipleLines"])

lb_InternetService = LabelEncoder()
df["InternetServicecode"] = lb_InternetService.fit_transform(df["InternetService"])

lb_OnlineSecurity = LabelEncoder()
df["OnlineSecuritycode"] = lb_InternetService.fit_transform(df["OnlineSecurity"])

lb_OnlineBackup = LabelEncoder()
df["OnlineBackupcode"] = lb_OnlineBackup.fit_transform(df["OnlineBackup"])

lb_DeviceProtection = LabelEncoder()
df["DeviceProtectioncode"] = lb_DeviceProtection.fit_transform(df["DeviceProtection"])

lb_TechSupport = LabelEncoder()
df["TechSupportcode"] = lb_TechSupport.fit_transform(df["TechSupport"])

lb_StreamingTV = LabelEncoder()
df["StreamingTVcode"] = lb_StreamingTV.fit_transform(df["StreamingTV"])

lb_StreamingMovies = LabelEncoder()
df["StreamingMoviescode"] = lb_StreamingMovies.fit_transform(df["StreamingMovies"])

lb_Contract = LabelEncoder()
df["Contractcode"] = lb_Contract.fit_transform(df["Contract"])

lb_PaperlessBilling = LabelEncoder()
df["PaperlessBillingcode"] = lb_PaperlessBilling.fit_transform(df["PaperlessBilling"])

lb_PaymentMethod = LabelEncoder()
df["PaymentMethodcode"] = lb_PaymentMethod.fit_transform(df["PaymentMethod"])

lb_Churn = LabelEncoder()
df["Churncode"] = lb_Churn.fit_transform(df["Churn"])

df.info()

#Downloading the final version of dataset into csv document
df.to_csv('dqlab_telco_encoded.csv', encoding='utf-8', index=False)
files.download('dqlab_telco_encoded.csv')